version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: "1"
    working_directory: ~/suplearn-clone-detection

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            pipenv install
            pipenv run pip install tensorflow
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: pipenv run python setup.py test
